fix: lock rust stable version to 1.77 (#1029)
Description
---
Lock rust version to 1.77

Motivation and Context
---
Rust 1.78 causes a mempory alignment panic in the version of wasmer we
use. For now we'll lock to 1.77.

https://github.com/wasmerio/wasmer/blob/2.3.0/lib/vm/src/instance/mod.rs#L968
Error: unsafe precondition(s) violated: ptr::copy_nonoverlapping
requires that both pointer arguments are aligned and non-null and the
specified memory ranges do not overlap

How Has This Been Tested?
---
CI

What process can a PR reviewer use to test or verify this change?
---
Wasm tests pass

Breaking Changes
---

- [x] None
- [ ] Requires data directory to be deleted
- [ ] Other - Please specify